### ISSUE TITLE
Change script to allow other services restarted as well

### ISSUE THREAD

**Issue by pboosten** [dlangille/anvil#6]
Currently, with every update of anvil I need to modify the script to allow for other services, not explicitly mentioned in the script, to be restarted as well.

Services are (for instance) mattermostd, courier-imap-imapd-ssl, sabnzbd and others.

**Comment by dlangille** [comment]
What? I have users?

**Comment by dlangille** [comment]
Yeah, I wonder how best to do this. Sounds like a hook-type thing.

Here, run 'this script'.

How would you prefer to handle it? A configuration item:

```
USER_RESTART="mattermostd courier-imap-imapd-ssl sabnzbd"
USER_RELOAD="foo bar"

for service in $USER_RESTART
do
  service $service restart
done

for service in $USER_RELOAD
do
  service $service reload
done

```

**Comment by pboosten** [comment]
Yeah! And I love it. 

 Cheers, Peter

**Comment by dlangille** [comment]
This is a security risk, but it's all up to the user.

**Comment by dlangille** [comment]
`certpuller -s` needs to be updated too.

**Comment by pboosten** [comment]
> This is a security risk, but it's all up to the user.

Not sure why this is a security risk: the script runs as anvil user, and as such it has no authorizations to restart whatever service, unless explicitly configured in sudoers

**Comment by dlangille** [comment]
I ran this through on one server.  Do you want to give it a go?

**Comment by pboosten** [comment]
Hi Dan,

Apologies for late answer: gonna try tonight

**Comment by dlangille** [comment]
It sounds like it worked.
